# https://github.com/brandtbucher/travis-python-matrix

# Just copy-and-paste any matrix entries you need!

matrix:

  include:

    - name: CPython 3.7.3 on Ubuntu 16.04 (Xenial Xerus)
      python: 3.7.3
      dist: xenial
      language: python

    - name: CPython 3.7.2 on Ubuntu 16.04 (Xenial Xerus)
      python: 3.7.2
      dist: xenial
      language: python

    - name: CPython 3.7.1 on Ubuntu 16.04 (Xenial Xerus)
      python: 3.7.1
      dist: xenial
      language: python

    - name: CPython 3.7.0 on Ubuntu 16.04 (Xenial Xerus)
      python: 3.7.0
      dist: xenial
      language: python

    - name: CPython 3.6.8 on Ubuntu 16.04 (Xenial Xerus)
      python: 3.6.8
      dist: xenial
      language: python

    - name: CPython 3.6.7 on Ubuntu 16.04 (Xenial Xerus)
      python: 3.6.7
      dist: xenial
      language: python

    - name: CPython 3.6.6 on Ubuntu 16.04 (Xenial Xerus)
      python: 3.6.6
      dist: xenial
      language: python

    - name: CPython 3.6.5 on Ubuntu 16.04 (Xenial Xerus)
      python: 3.6.5
      dist: xenial
      language: python

    - name: CPython 3.6.4 on Ubuntu 16.04 (Xenial Xerus)
      python: 3.6.4
      dist: xenial
      language: python

    - name: CPython 3.6.3 on Ubuntu 16.04 (Xenial Xerus)
      python: 3.6.3
      dist: xenial
      language: python

    - name: CPython 3.5.2 on Ubuntu 16.04 (Xenial Xerus)
      python: 3.5.2
      dist: xenial
      language: python

    - name: CPython 3.7.3 on Windows Server 1803
      os: windows
      before_install: choco install python --version 3.7.3
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      language: shell

    - name: CPython 3.7.2 on Windows Server 1803
      os: windows
      before_install: choco install python --version 3.7.2
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      language: shell

    - name: CPython 3.7.1 on Windows Server 1803
      os: windows
      before_install: choco install python --version 3.7.1
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      language: shell

    - name: CPython 3.7.0 on Windows Server 1803
      os: windows
      before_install: choco install python --version 3.7.0
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      language: shell

    - name: CPython 3.6.8 on Windows Server 1803
      os: windows
      before_install: choco install python --version 3.6.8
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
      language: shell

    - name: CPython 3.6.7 on Windows Server 1803
      os: windows
      before_install: choco install python --version 3.6.7
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
      language: shell

    - name: CPython 3.6.6 on Windows Server 1803
      os: windows
      before_install: choco install python --version 3.6.6
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
      language: shell

    - name: CPython 3.6.5 on Windows Server 1803
      os: windows
      before_install: choco install python --version 3.6.5
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
      language: shell

    - name: CPython 3.6.4 on Windows Server 1803
      os: windows
      before_install: choco install python --version 3.6.4
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
      language: shell

    - name: CPython 3.6.3 on Windows Server 1803
      os: windows
      before_install: choco install python --version 3.6.3
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
      language: shell

    - name: CPython 3.5.2 on Windows Server 1803
      os: windows
      before_install: choco install python --version 3.5.2.20161029
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
      language: shell

    - name: CPython 3.7.3 on macOS 10.14 (Mojave)
      os: osx
      osx_image: xcode10.2
      before_install: CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7.3
      language: shell

    - name: CPython 3.7.2 on macOS 10.14 (Mojave)
      os: osx
      osx_image: xcode10.2
      before_install: CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7.2
      language: shell

    - name: CPython 3.7.1 on macOS 10.14 (Mojave)
      os: osx
      osx_image: xcode10.2
      before_install: CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7.1
      language: shell

    - name: CPython 3.7.0 on macOS 10.14 (Mojave)
      os: osx
      osx_image: xcode10.2
      before_install: CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7.0
      language: shell

    - name: CPython 3.6.8 on macOS 10.14 (Mojave)
      os: osx
      osx_image: xcode10.2
      before_install: CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.8
      language: shell

    - name: CPython 3.6.7 on macOS 10.14 (Mojave)
      os: osx
      osx_image: xcode10.2
      before_install: CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.7
      language: shell

    - name: CPython 3.6.6 on macOS 10.14 (Mojave)
      os: osx
      osx_image: xcode10.2
      before_install: CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.6
      language: shell

    - name: CPython 3.6.5 on macOS 10.14 (Mojave)
      os: osx
      osx_image: xcode10.2
      before_install: CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.5
      language: shell

    - name: CPython 3.6.4 on macOS 10.14 (Mojave)
      os: osx
      osx_image: xcode10.2
      before_install: CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.4
      language: shell

    - name: CPython 3.6.3 on macOS 10.14 (Mojave)
      os: osx
      osx_image: xcode10.2
      before_install: CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.3
      language: shell

    - name: CPython 3.5.2 on macOS 10.14 (Mojave)
      os: osx
      osx_image: xcode10.2
      before_install: CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.5.2
      language: shell

    - name: CPython 3.7.3 on macOS 10.13 (High Sierra)
      os: osx
      osx_image: xcode10.1
      before_install: brew upgrade pyenv && pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7.3
      language: shell

    - name: CPython 3.7.2 on macOS 10.13 (High Sierra)
      os: osx
      osx_image: xcode10.1
      before_install: brew upgrade pyenv && pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7.2
      language: shell

    - name: CPython 3.7.1 on macOS 10.13 (High Sierra)
      os: osx
      osx_image: xcode10.1
      before_install: pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7.1
      language: shell

    - name: CPython 3.7.0 on macOS 10.13 (High Sierra)
      os: osx
      osx_image: xcode10.1
      before_install: pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7.0
      language: shell

    - name: CPython 3.6.8 on macOS 10.13 (High Sierra)
      os: osx
      osx_image: xcode10.1
      before_install: brew upgrade pyenv && pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.8
      language: shell

    - name: CPython 3.6.7 on macOS 10.13 (High Sierra)
      os: osx
      osx_image: xcode10.1
      before_install: pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.7
      language: shell

    - name: CPython 3.6.6 on macOS 10.13 (High Sierra)
      os: osx
      osx_image: xcode10.1
      before_install: pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.6
      language: shell

    - name: CPython 3.6.5 on macOS 10.13 (High Sierra)
      os: osx
      osx_image: xcode10.1
      before_install: pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.5
      language: shell

    - name: CPython 3.6.4 on macOS 10.13 (High Sierra)
      os: osx
      osx_image: xcode10.1
      before_install: pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.4
      language: shell

    - name: CPython 3.6.3 on macOS 10.13 (High Sierra)
      os: osx
      osx_image: xcode10.1
      before_install: pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.3
      language: shell

    - name: CPython 3.5.2 on macOS 10.13 (High Sierra)
      os: osx
      osx_image: xcode10.1
      before_install: pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.5.2
      language: shell

    - name: CPython 3.7.3 on macOS 10.12 (Sierra)
      os: osx
      osx_image: xcode9.2
      before_install: brew upgrade pyenv && pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7.3
      language: shell

    - name: CPython 3.7.2 on macOS 10.12 (Sierra)
      os: osx
      osx_image: xcode9.2
      before_install: brew upgrade pyenv && pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7.2
      language: shell

    - name: CPython 3.7.1 on macOS 10.12 (Sierra)
      os: osx
      osx_image: xcode9.2
      before_install: brew upgrade pyenv && pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7.1
      language: shell

    - name: CPython 3.7.0 on macOS 10.12 (Sierra)
      os: osx
      osx_image: xcode9.2
      before_install: brew upgrade pyenv && pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7.0
      language: shell

    - name: CPython 3.6.8 on macOS 10.12 (Sierra)
      os: osx
      osx_image: xcode9.2
      before_install: brew upgrade pyenv && pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.8
      language: shell

    - name: CPython 3.6.7 on macOS 10.12 (Sierra)
      os: osx
      osx_image: xcode9.2
      before_install: brew upgrade pyenv && pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.7
      language: shell

    - name: CPython 3.6.6 on macOS 10.12 (Sierra)
      os: osx
      osx_image: xcode9.2
      before_install: brew upgrade pyenv && pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.6
      language: shell

    - name: CPython 3.6.5 on macOS 10.12 (Sierra)
      os: osx
      osx_image: xcode9.2
      before_install: brew upgrade pyenv && pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.5
      language: shell

    - name: CPython 3.6.4 on macOS 10.12 (Sierra)
      os: osx
      osx_image: xcode9.2
      before_install: brew upgrade pyenv && pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.4
      language: shell

    - name: CPython 3.6.3 on macOS 10.12 (Sierra)
      os: osx
      osx_image: xcode9.2
      before_install: pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.3
      language: shell

    - name: CPython 3.5.2 on macOS 10.12 (Sierra)
      os: osx
      osx_image: xcode9.2
      before_install: pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.5.2
      language: shell


# Change anything below to suit your CI needs.

# Python and pip exectuables are just named "python" and "pip" on all platforms!

install: pip --version

script: python --version
